[2023-11-25T07:02:54.430+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_DAG.TRANSFORM_DATA scheduled__2023-11-24T00:00:00+00:00 [queued]>
[2023-11-25T07:02:54.441+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_DAG.TRANSFORM_DATA scheduled__2023-11-24T00:00:00+00:00 [queued]>
[2023-11-25T07:02:54.441+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-25T07:02:54.465+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): TRANSFORM_DATA> on 2023-11-24 00:00:00+00:00
[2023-11-25T07:02:54.471+0000] {standard_task_runner.py:57} INFO - Started process 93 to run task
[2023-11-25T07:02:54.475+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_DAG', 'TRANSFORM_DATA', 'scheduled__2023-11-24T00:00:00+00:00', '--job-id', '60', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_DAG.py', '--cfg-path', '/tmp/tmpcwr_oufd']
[2023-11-25T07:02:54.480+0000] {standard_task_runner.py:85} INFO - Job 60: Subtask TRANSFORM_DATA
[2023-11-25T07:02:54.547+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_DAG.TRANSFORM_DATA scheduled__2023-11-24T00:00:00+00:00 [running]> on host f51528ecf28c
[2023-11-25T07:02:54.649+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='devyani.srivastava' AIRFLOW_CTX_DAG_ID='outcomes_DAG' AIRFLOW_CTX_TASK_ID='TRANSFORM_DATA' AIRFLOW_CTX_EXECUTION_DATE='2023-11-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-24T00:00:00+00:00'
[2023-11-25T07:02:58.438+0000] {warnings.py:109} WARNING - /opt/***/dags/ETL/transform.py:103: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  data['ts'] = pd.to_datetime(data.DateTime)

[2023-11-25T07:03:20.495+0000] {warnings.py:109} WARNING - /opt/***/dags/ETL/transform.py:121: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  animal_dim['sex']=animal_dim['sex'].fillna(mode_sex)

[2023-11-25T07:03:26.894+0000] {logging_mixin.py:154} INFO - DataFrame uploaded successfully to dcsctransformdata/dim_animals.csv
[2023-11-25T07:03:27.715+0000] {logging_mixin.py:154} INFO - DataFrame uploaded successfully to dcsctransformdata/dim_dates.csv
[2023-11-25T07:03:28.348+0000] {logging_mixin.py:154} INFO - DataFrame uploaded successfully to dcsctransformdata/dim_outcome_types.csv
[2023-11-25T07:03:32.032+0000] {logging_mixin.py:154} INFO - DataFrame uploaded successfully to dcsctransformdata/fct_outcomes.csv
[2023-11-25T07:03:32.096+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-25T07:03:32.117+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=outcomes_DAG, task_id=TRANSFORM_DATA, execution_date=20231124T000000, start_date=20231125T070254, end_date=20231125T070332
[2023-11-25T07:03:32.169+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-25T07:03:32.207+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
